export const PLATFORM_NAMES = {
  '1292-programmable': '1292 Advanced Programmable Video System',
  '3do': '3DO',
  '3ds': 'Nintendo 3DS',
  'acorn-32-bit': 'Acorn 32-bit',
  air: 'AirConsole',
  alexa: 'Amazon Alexa',
  alice: 'Alice 32/90',
  altair680: 'Altair 680',
  altair8800: 'Altair 8800',
  'amiga-cd32': 'Amiga CD32',
  amiga: 'Amiga',
  'amstrad-pcw': 'Amstrad PCW',
  android: 'Android',
  antstream: 'Antstream',
  'apf-mp1000': 'APF MP1000/Imagination Machine',
  apple1: 'Apple I',
  apple2: 'Apple II',
  apple2gs: 'Apple IIgs',
  arcade: 'Arcade',
  arcadia2001: 'Arcadia 2001',
  Arduboy: 'Arduboy',
  astral2000: 'Astral 2000',
  'atari-2600': 'Atari 2600',
  'atari-5200': 'Atari 5200',
  'atari-7800': 'Atari 7800',
  'atari-8-bit': 'Atari 8-bit',
  'atari-st': 'Atari ST',
  Atom: 'Atom',
  av: 'Adventure Vision',
  bada: 'bada',
  'Bally Astrocade': 'Bally Astrocade',
  'BBC Micro': 'BBC Micro',
  BeOS: 'BeOS',
  blackberry: 'BlackBerry',
  blacknut: 'Blacknut',
  Blacknut: 'Blacknut',
  'Blu-ray Disc Player': 'Blu-ray Disc Player',
  brew: 'BREW',
  browser: 'Browser',
  Browser: 'Browser',
  Bubble: 'Bubble',
  c64: 'Commodore 64',
  'Camputers Lynx': 'Camputers Lynx',
  'Casio Loopy': 'Casio Loopy',
  'Casio Programmable Calculator': 'Casio Programmable Calculator',
  'Casio PV-1000': 'Casio PV-1000',
  'cd-i': 'CD-i',
  CDTV: 'CDTV',
  'Champion 2711': 'Champion 2711',
  'Channel F': 'Channel F',
  ClickStart: 'ClickStart',
  'Coleco Adam': 'Coleco Adam',
  colecovision: 'ColecoVision',
  'Colour Genie': 'Colour Genie',
  'Commodore 128': 'Commodore 128',
  'commodore-16-plus4': 'Commodore 16, Plus/4',
  'Compal 80': 'Compal 80',
  'Compucolor I': 'Compucolor I',
  'Compucolor II': 'Compucolor II',
  Compucorp: 'Compucorp Programmable Calculator',
  COSMAC: 'COSMAC',
  'CP/M': 'CP/M',
  cpc: 'Amstrad CPC',
  CreatiVision: 'CreatiVision',
  Cybervision: 'Cybervision',
  'Danger OS': 'Danger OS',
  'dedicated-console': 'Dedicated console',
  'dedicated-handheld': 'Dedicated handheld',
  Didj: 'Didj',
  digiBlast: 'digiBlast',
  doja: 'DoJa',
  dos: 'DOS',
  'dragon-3264': 'Dragon 32/64',
  dreamcast: 'Dreamcast',
  'dvd-player': 'DVD Player',
  'ECD Micromind': 'ECD Micromind',
  electron: 'Electron',
  Enterprise: 'Enterprise',
  'Epoch Cassette Vision': 'Epoch Cassette Vision',
  'Epoch Game Pocket Computer': 'Epoch Game Pocket Computer',
  'Epoch Super Cassette Vision': 'Epoch Super Cassette Vision',
  Evercade: 'Evercade',
  Exelvision: 'Exelvision',
  ExEn: 'ExEn',
  'Exidy Sorcerer': 'Exidy Sorcerer',
  'Fire OS': 'Fire OS',
  'fm-7': 'FM-7',
  fmtowns: 'FM Towns',
  Freebox: 'Freebox',
  'G-cluster': 'G-cluster',
  Galaksija: 'Galaksija',
  'Game Wave': 'Game Wave',
  'game-gear': 'Game Gear',
  'Game.Com': 'Game.Com',
  'gameboy-advance': 'Game Boy Advance',
  'gameboy-color': 'Game Boy Color',
  gameboy: 'Game Boy',
  gamecube: 'GameCube',
  GameStick: 'GameStick',
  genesis: 'SEGA Mega Drive',
  GIMINI: 'GIMINI',
  Gizmondo: 'Gizmondo',
  Gloud: 'Gloud',
  Glulx: 'Glulx',
  GNEX: 'GNEX',
  'GP2X Wiz': 'GP2X Wiz',
  GP2X: 'GP2X',
  GP32: 'GP32',
  GVM: 'GVM',
  'HD DVD Player': 'HD DVD Player',
  'Heath/Zenith H8/H89': 'Heath/Zenith H8/H89',
  'Heathkit H11': 'Heathkit H11',
  'Hitachi S1': 'Hitachi S1',
  'HP 9800': 'HP 9800',
  'HP Programmable Calculator': 'HP Programmable Calculator',
  Hugo: 'Hugo',
  HyperScan: 'HyperScan',
  'IBM 5100': 'IBM 5100',
  'Ideal-Computer': 'Ideal-Computer',
  'Intel 8008': 'Intel 8008',
  'Intel 8080': 'Intel 8080',
  intellivision: 'Intellivision',
  'Interact Model One': 'Interact Model One',
  'Interton Video 2000': 'Interton Video 2000',
  ipad: 'iPad',
  iPad: 'iPad',
  iphone: 'iPhone',
  'iPod Classic': 'iPod Classic',
  j2me: 'J2ME',
  Jaguar: 'Jaguar',
  Jolt: 'Jolt',
  'Jupiter Ace': 'Jupiter Ace',
  'KIM-1': 'KIM-1',
  'Kindle Classic': 'Kindle Classic',
  'Laser 200': 'Laser 200',
  LaserActive: 'LaserActive',
  'LeapFrog Explorer': 'LeapFrog Explorer',
  Leapster: 'Leapster',
  LeapTV: 'LeapTV',
  linux: 'Linux',
  Luna: 'Luna',
  Lynx: 'Lynx',
  macintosh: 'Macintosh',
  Maemo: 'Maemo',
  mainframe: 'Mainframe',
  'Matsushita/Panasonic JR': 'Matsushita/Panasonic JR',
  'Mattel Aquarius': 'Mattel Aquarius',
  MeeGo: 'MeeGo',
  'Memotech MTX': 'Memotech MTX',
  Meritum: 'Meritum',
  Microbee: 'Microbee',
  'Microtan 65': 'Microtan 65',
  Microvision: 'Microvision',
  Mophun: 'Mophun',
  'MOS Technology 6502': 'MOS Technology 6502',
  'Motorola 6800': 'Motorola 6800',
  'Motorola 68k': 'Motorola 68k',
  MRE: 'MRE',
  msx: 'MSX',
  'N-Gage (service)': 'N-Gage (service)',
  'N-Gage': 'N-Gage',
  n64: 'Nintendo 64',
  Nascom: 'Nascom',
  'Neo Geo CD': 'Neo Geo CD',
  'Neo Geo Pocket Color': 'Neo Geo Pocket Color',
  'Neo Geo Pocket': 'Neo Geo Pocket',
  'Neo Geo X': 'Neo Geo X',
  'Neo Geo': 'Neo Geo',
  nes: 'NES',
  'new-nintendo-3ds': 'New Nintendo 3DS',
  NewBrain: 'NewBrain',
  Newton: 'Newton',
  'nintendo-ds': 'Nintendo DS',
  'nintendo-dsi': 'Nintendo DSi',
  'North Star': 'North Star',
  'Noval 760': 'Noval 760',
  Nuon: 'Nuon',
  'oculus-go': 'Oculus Go',
  'oculus-quest': 'Oculus Quest',
  'Odyssey 2': 'Odyssey 2',
  Odyssey: 'Odyssey',
  'Ohio Scientific': 'Ohio Scientific',
  onlive: 'OnLive',
  OOParts: 'OOParts',
  Orao: 'Orao',
  Oric: 'Oric',
  'OS/2': 'OS/2',
  ouya: 'Ouya',
  palmos: 'Palm OS',
  Pandora: 'Pandora',
  'PC-6001': 'PC-6001',
  'PC-8000': 'PC-8000',
  'pc-booter': 'PC Booter',
  'PC-FX': 'PC-FX',
  pc88: 'PC-88',
  pc98: 'PC-98',
  Pebble: 'Pebble',
  pet: 'Commodore PET/CBM',
  'Philips VG 5000': 'Philips VG 5000',
  'Photo CD': 'Photo CD',
  Pippin: 'Pippin',
  Playdate: 'Playdate',
  Playdia: 'Playdia',
  'PlayStation Now': 'PlayStation Now',
  'Plex Arcade': 'Plex Arcade',
  'Pokémon Mini': 'Pokémon Mini',
  Pokitto: 'Pokitto',
  'Poly-88': 'Poly-88',
  'ps-vita': 'PS Vita',
  ps2: 'PlayStation 2',
  ps3: 'PlayStation 3',
  ps4: 'PlayStation 4',
  ps5: 'PlayStation 5',
  psp: 'PSP',
  psx: 'PlayStation',
  'RCA Studio II': 'RCA Studio II',
  'Research Machines 380Z': 'Research Machines 380Z',
  Roku: 'Roku',
  'SAM Coupé': 'SAM Coupé',
  'SC/MP': 'SC/MP',
  'SD-200/270/290': 'SD-200/270/290',
  'SEGA Pico': 'SEGA Pico',
  'sega-32x': 'SEGA 32X',
  'sega-cd': 'SEGA CD',
  'sega-master-system': 'SEGA Master System',
  'sega-saturn': 'SEGA Saturn',
  'SG-1000': 'SG-1000',
  'Sharp MZ-80B/2000/2500': 'Sharp MZ-80B/2000/2500',
  'Sharp MZ-80K/700/800/1500': 'Sharp MZ-80K/700/800/1500',
  'Sharp Zaurus': 'Sharp Zaurus',
  'sharp-x1': 'Sharp X1',
  'sharp-x68000': 'Sharp X68000',
  'Signetics 2650': 'Signetics 2650',
  'Sinclair QL': 'Sinclair QL',
  'SK-VM': 'SK-VM',
  'SMC-777': 'SMC-777',
  snes: 'SNES',
  SNES: 'SNES',
  Socrates: 'Socrates',
  'sol-20': 'Sol-20',
  'Sord M5': 'Sord M5',
  Spectravideo: 'Spectravideo',
  'SRI-500/1000': 'SRI-500/1000',
  stadia: 'Stadia',
  'Super Vision 8000': 'Super Vision 8000',
  SuperGrafx: 'SuperGrafx',
  Supervision: 'Supervision',
  'Sure Shot HD': 'Sure Shot HD',
  switch: 'Nintendo Switch',
  'SWTPC 6800': 'SWTPC 6800',
  symbian: 'Symbian',
  TADS: 'TADS',
  'Taito X-55': 'Taito X-55',
  'Tatung Einstein': 'Tatung Einstein',
  'Tektronix 4050': 'Tektronix 4050',
  'Tele-Spiel ES-2201': 'Tele-Spiel ES-2201',
  'Telstar Arcade': 'Telstar Arcade',
  Terminal: 'Terminal',
  'Thomson MO': 'Thomson MO',
  'Thomson TO': 'Thomson TO',
  'TI Programmable Calculator': 'TI Programmable Calculator',
  'ti-994a': 'TI-99/4A',
  'Tiki 100': 'Tiki 100',
  TIM: 'TIM',
  'Timex Sinclair 2068': 'Timex Sinclair 2068',
  Tizen: 'Tizen',
  'Tomahawk F1': 'Tomahawk F1',
  'Tomy Tutor': 'Tomy Tutor',
  Triton: 'Triton',
  'TRS-80 MC-10': 'TRS-80 MC-10',
  'TRS-80 Model 100': 'TRS-80 Model 100',
  'trs-80-coco': 'TRS-80 CoCo',
  'trs-80': 'TRS-80',
  'turbo-grafx': 'TurboGrafx-16',
  'turbografx-cd': 'TurboGrafx CD',
  tvos: 'tvOS',
  'V.Flash': 'V.Flash',
  'V.Smile': 'V.Smile',
  Vectrex: 'Vectrex',
  Versatile: 'Versatile',
  'vic-20': 'VIC-20',
  VideoBrain: 'VideoBrain',
  'Videopac+ G7400': 'Videopac+ G7400',
  'Virtual Boy': 'Virtual Boy',
  VIS: 'VIS',
  'Wang 2200': 'Wang 2200',
  watchOS: 'watchOS',
  webOS: 'webOS',
  'wii-u': 'Wii U',
  wii: 'Wii',
  win3x: 'Windows 3.x',
  'windows-apps': 'Windows Apps',
  'windows-phone': 'Windows Phone',
  windows: 'Windows',
  windowsmobile: 'Windows Mobile',
  WIPI: 'WIPI',
  'WonderSwan Color': 'WonderSwan Color',
  WonderSwan: 'WonderSwan',
  XaviXPORT: 'XaviXPORT',
  'Xbox Series': 'Xbox Series',
  'xbox-one': 'Xbox One',
  'xbox-series': 'Xbox Series',
  xbox: 'Xbox',
  xbox360: 'Xbox 360',
  xboxcloudgaming: 'Xbox Cloud Gaming',
  'Xerox Alto': 'Xerox Alto',
  'Z-machine': 'Z-machine',
  Zeebo: 'Zeebo',
  'Zilog Z80': 'Zilog Z80',
  'Zilog Z8000': 'Zilog Z8000',
  Zodiac: 'Zodiac',
  Zune: 'Zune',
  'ZX Spectrum Next': 'ZX Spectrum Next',
  'zx-spectrum': 'ZX Spectrum',
  ZX80: 'ZX80',
  zx81: 'ZX81',
  "Super A'can": "Super A'can",
} as const;
