export const PLATFORM_NAMES = {
  '3do': '3DO',
  'acorn-32-bit': 'Acorn 32-bit',
  amiga: 'Amiga',
  'amiga-cd32': 'Amiga CD32',
  cpc: 'Amstrad CPC',
  'amstrad-pcw': 'Amstrad PCW',
  android: 'Android',
  antstream: 'Antstream',
  apple2: 'Apple II',
  apple2gs: 'Apple IIgs',
  arcade: 'Arcade',
  'atari-2600': 'Atari 2600',
  'atari-8-bit': 'Atari 8-bit',
  'atari-st': 'Atari ST',
  'bbc-micro_': 'BBC Micro',
  brew: 'BREW',
  blackberry: 'BlackBerry',
  blacknut: 'Blacknut',
  browser: 'Browser',
  'cd-i': 'CD-i',
  colecovision: 'ColecoVision',
  'commodore-16-plus4': 'Commodore 16, Plus/4',
  c64: 'Commodore 64',
  pet: 'Commodore PET/CBM',
  dos: 'DOS',
  'dvd-player': 'DVD Player',
  'dedicated-console': 'Dedicated console',
  'dedicated-handheld': 'Dedicated handheld',
  doja: 'DoJa',
  'dragon-3264': 'Dragon 32/64',
  dreamcast: 'Dreamcast',
  electron: 'Electron',
  fmtowns: 'FM Towns',
  'fm-7': 'FM-7',
  gameboy: 'Game Boy',
  'gameboy-advance': 'Game Boy Advance',
  'gameboy-color': 'Game Boy Color',
  'game-gear': 'Game Gear',
  gamecube: 'GameCube',
  genesis: 'SEGA Mega Drive',
  intellivision: 'Intellivision',
  j2me: 'J2ME',
  linux: 'Linux',
  msx: 'MSX',
  macintosh: 'Macintosh',
  mainframe: 'Mainframe',
  nes: 'NES',
  'new-nintendo-3ds': 'New Nintendo 3DS',
  '3ds': 'Nintendo 3DS',
  n64: 'Nintendo 64',
  'nintendo-ds': 'Nintendo DS',
  'nintendo-dsi': 'Nintendo DSi',
  switch: 'Nintendo Switch',
  'oculus-go': 'Oculus Go',
  'oculus-quest': 'Oculus Quest',
  onlive: 'OnLive',
  ouya: 'Ouya',
  'pc-booter': 'PC Booter',
  pc88: 'PC-88',
  pc98: 'PC-98',
  'ps-vita': 'PS Vita',
  psp: 'PSP',
  palmos: 'Palm OS',
  playstation: 'PlayStation',
  ps2: 'PlayStation 2',
  ps3: 'PlayStation 3',
  'playstation-4': 'PlayStation 4',
  'playstation-5': 'PlayStation 5',
  'sega-cd': 'SEGA CD',
  'sega-master-system': 'SEGA Master System',
  'sega-saturn': 'SEGA Saturn',
  snes: 'SNES',
  'sharp-x1': 'Sharp X1',
  'sharp-x68000': 'Sharp X68000',
  'sol-20': 'Sol-20',
  stadia: 'Stadia',
  symbian: 'Symbian',
  'ti-994a': 'TI-99/4A',
  'trs-80': 'TRS-80',
  'trs-80-coco': 'TRS-80 CoCo',
  'turbografx-cd': 'TurboGrafx CD',
  'turbo-grafx': 'TurboGrafx-16',
  'vic-20': 'VIC-20',
  wii: 'Wii',
  'wii-u': 'Wii U',
  windows: 'Windows',
  win3x: 'Windows 3.x',
  'windows-apps': 'Windows Apps',
  windowsmobile: 'Windows Mobile',
  'windows-phone': 'Windows Phone',
  xbox: 'Xbox',
  xbox360: 'Xbox 360',
  xboxcloudgaming: 'Xbox Cloud Gaming',
  'xbox-one': 'Xbox One',
  'xbox-series': 'Xbox Series',
  'zx-spectrum': 'ZX Spectrum',
  zx81: 'ZX81',
  ipad: 'iPad',
  iphone: 'iPhone',
  tvos: 'tvOS',
};
